config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    resources :relationships, only: [:index]
  end
  resources :relationships, only: [:create, :destroy]
  resources :words
  resources :user_words, only: [:create, :destroy]
  resources :categories, only: [:index] do
    resources :lessons, only: [:show, :create, :update]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, t(:about)) %>
<h1>About</h1>
<p>
  This is the E learning application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, t(:contact)) %>
<h1>Contact</h1>
<p>
  Contact me at
  <a href="http://recruit.framgia.vn">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, t(:help)) %>
<h1>Help</h1>
<p>
  Please ask me for every thing.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, t(:home)) %>  
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <%= link_to t(:word_list), words_path, class: "btn btn-lg btn-primary" %>
    <%= link_to t(:Categories), categories_path, class: "btn btn-lg btn-primary" %>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the ELS application</h1>
    <h2>
      This is the home page for the E learning system application.
    </h2>
    <%= link_to t(:signup), signup_path, class: "btn btn-lg btn-primary" %>
  </div>

<% end %>