config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    resources :relationships, only: [:index]
  end
  resources :relationships, only: [:create, :destroy]
  resources :words
  resources :user_words, only: [:create, :destroy]
  resources :categories, only: [:index] do
    resources :lessons, only: [:show, :create, :update]
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to user_relationships_path(user_id: @user.id, option: "following") do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t :following%>
  <%end %>
  <%= link_to user_relationships_path(user_id: @user.id, option: "followers") do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t :followers%>
  <%end %>
  <%= link_to '#' do %>
    <strong id="followers" class="stat">
      <%= @user.UserWords.count %>
    </strong>
    <%= t :has_learn_words%>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(:view_profile), current_user %></span>