config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    resources :relationships, only: [:index]
  end
  resources :relationships, only: [:create, :destroy]
  resources :words
  resources :user_words, only: [:create, :destroy]
  resources :categories, only: [:index] do
    resources :lessons, only: [:show, :create, :update]
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  has_many :user_words, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true
  validates :content_jp, presence: true, length: { maximum: 50 },
                        uniqueness: {case_sensitive: false}
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :admin_user,     only: [:create, :destroy]
  
  def index
    @words = Word.paginate page: params[:page]
  end

  def show
    @word = Word.find params[:id]
    @answers = @word.answers
    @user_word = current_user.user_words.build 
  end

  def new
    @word = Word.new
    4.times { @word.answers.build }
  end

  def create
    @word = Word.new word_params 
    if @word.save
      flash[:success] = t :create_word_success
      redirect_to words_url
    else
      render 'create'
    end
  end

  def destroy
    Word.find(params[:id]).destroy
    flash[:success] = t :word_deleted
    redirect_to words_url
  end

  private
  def word_params
    params.require(:word).permit(:content_jp,
                          answers_attributes: [:content, :correct_answer])
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_word.html.erb
<li>
  <%= link_to word.content_jp, word %>
  <% if current_user.admin? %>
    | <%= link_to t(:delete), word, method: :delete, 
                   			data: { confirm: t(:you_sure) } %>
  <% end %>
  <% if current_user.learned? word %>
    | <%= t(:learned) %> 
  <% end %>
</li>

app/views/words/index.html.erb
<% provide(:title, t(:all_word))%>
<% if current_user.admin? %>
<%= link_to t(:creat_word), new_word_path, class: "btn btn-lg btn-primary" %>
<% end %>
<h1>All words</h1>
<%= will_paginate %>
<ul class="words">
  <%= render @words %>
</ul>
<%= will_paginate %>

app/views/words/new.html.erb
<% provide(:title, t(:creat_word)) %>
<h1>Create word</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @word do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= label(:word, :content_jp)%>
      <%= f.text_field :content_jp, class: 'form-control' %>

      <p class="fields">
        <%= f.fields_for :answers do |builder| %>
          <%= label(:word, :answer) %>
          <%= builder.text_field :content, class: 'form-control' %>
          <%= builder.hidden_field :correct_answer, value: :true%>
          <%= label(:word, :correct_answer, class: "checkbox inline") do %>
            <%= builder.check_box :correct_answer %>
            <%= label(:word, :correct_answer)%>
      <% end %>
        <% end %>
      </p>
      <%= f.submit t(:creat_word), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/words/show.html.erb
<% provide(:title, @word.content_jp) %>
<div class="row">
  <div class="col-md-4">
    <section>
      <h1>
        Japanese mean
      </h1>
      <h1>
        <%= @word.content_jp %>
      </h1>
    </section>
  </div>
  <div class="col-md-8">
    <section>
      <h1>
        Vietnamese mean
      </h1>
      <h2>
        <% @answers.each do |answer| %>
          <%= answer.content if answer.correct_answer%>
        <% end %>
      </h2>
    </section>
  </div>
  <% if current_user.learned? @word %>
  <% else %>
    <%= form_for @user_word do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.hidden_field :word_id, value: @word.id%>
      <%= f.submit t(:learned), class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>